services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Jaggle\QueueBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests,Kernel.php,RedisJob.php}'

    Jaggle\QueueBundle\Service\QueueManager:
        arguments:
            $type: Jaggle\QueueBundle\RedisQueue